import { applyDecorators } from '@nestjs/common';
import { plainToInstance, Transform, Type } from 'class-transformer';
import {
  IsBoolean,
  IsEmail,
  IsFQDN,
  IsIn,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  Matches,
  Max,
  Min,
  MinLength,
  registerDecorator,
  ValidateIf,
  validateSync,
  type ValidationArguments,
} from 'class-validator';

import { DEFAULT_MAIL_OUTBOX_DIR } from 'src/mail/file-mail.transport';
import {
  MAIL_TRANSPORT_NAMES,
  SENDING_TRANSPORT,
  type MailTransportName,
} from 'src/mail/mail-transport-name';

/**
 * Scheme and host, nothing after them. The mail skeleton joins paths onto this
 * value with the URL parser, which drops any path prefix of the base: a
 * FRONTEND_URL of "https://example.fr/app" would silently produce links to
 * https://example.fr/… — right host, wrong site, and nothing to notice it by
 * until a reader clicks. Refusing it at bootstrap is the only place the
 * mistake is visible.
 */
const ORIGIN_ONLY = /^https?:\/\/[^/?#]+\/?$/;

const NODE_ENV_NAMES = ['development', 'test', 'production'] as const;

/**
 * Where the application listens when nothing says otherwise. They live here
 * rather than at the call site of app.listen(), because this is the file that
 * answers "what is this variable and what happens if I leave it out" — and one
 * default written in two places is one of them going stale.
 *
 * Outside code there are two more spellings of each, and they are meant to be
 * there: the line of .env.example and the port published by docker-compose.
 * Those are the ones to change together with these.
 */
const DEFAULT_PORT = 3001;
const DEFAULT_HOST = '0.0.0.0';

/**
 * A TCP port as it arrives from the environment: a string, which has to become
 * a number before any bound means anything. Both ports are declared with this
 * because the range is what a port *is*, not a policy of ours — and 0, the
 * value the bound below excludes, means "let the kernel pick one", which is
 * never what a service that has to be reachable wants.
 */
const MAX_PORT = 65535;
const IsPortNumber = () =>
  applyDecorators(
    Type(() => Number),
    IsInt(),
    Min(1),
    Max(MAX_PORT),
  );

/**
 * A secret of ours — all three are generated by `openssl rand -base64 48`
 * (.env.example), which yields 64 characters and clears this floor twice over.
 * The check therefore never fires on a real value: it exists for the one typed
 * by hand in a hurry, and for a "changeme" left from the example file.
 */
const MIN_SECRET_LENGTH = 32;
const IsSecret = () =>
  applyDecorators(IsString(), MinLength(MIN_SECRET_LENGTH));

const sendsForReal = (env: EnvironmentVariables): boolean =>
  env.MAIL_TRANSPORT === SENDING_TRANSPORT;

/**
 * Refuses a production start that would write emails to the local outbox
 * instead of sending them. The application would come up perfectly healthy and
 * every notification would land in a file: nobody is told an arrêté was
 * published, and the reader finds out by missing the 30-day deadline. The
 * transport left unset counts as local, because that is what the factory makes
 * of it.
 */
function SendsForRealInProduction() {
  return (object: object, propertyName: string): void => {
    registerDecorator({
      name: 'sendsForRealInProduction',
      target: object.constructor,
      propertyName,
      validator: {
        validate: (value: unknown, args: ValidationArguments): boolean =>
          value !== 'production' ||
          sendsForReal(args.object as EnvironmentVariables),
        defaultMessage: () =>
          `MAIL_TRANSPORT must be "${SENDING_TRANSPORT}" when NODE_ENV is production: the local transport writes messages to files and sends nothing`,
      },
    });
  };
}

/** Domains are case-insensitive; the part after the last @ is the domain. */
const domainOf = (address: string): string =>
  address.slice(address.lastIndexOf('@') + 1).toLowerCase();

/**
 * Refuses a sender address outside the domain configured as verified at the
 * provider — insurance against a typo in MAIL_FROM, which otherwise costs
 * nothing at bootstrap and every message afterwards: the provider refuses mail
 * from a domain it has not verified, one send at a time, while the application
 * stays perfectly healthy. The real protection from someone else's domain is
 * the provider's; this is the check that makes our own mistake visible.
 *
 * Exact equality, because that is what the provider verifies: a subdomain is a
 * separate domain to it. Nothing to compare against means nothing to refuse —
 * a fresh clone writes its messages to files and names no domain of ours.
 */
function AtSenderDomain() {
  return (object: object, propertyName: string): void => {
    registerDecorator({
      name: 'atSenderDomain',
      target: object.constructor,
      propertyName,
      validator: {
        validate: (value: unknown, args: ValidationArguments): boolean => {
          const domain = (
            args.object as EnvironmentVariables
          ).MAIL_SENDER_DOMAIN?.trim();
          return (
            !domain ||
            (typeof value === 'string' &&
              domainOf(value) === domain.toLowerCase())
          );
        },
        defaultMessage: () =>
          'MAIL_FROM must be an address at MAIL_SENDER_DOMAIN: the provider refuses a sender outside the domain verified with it, and a subdomain is not that domain',
      },
    });
  };
}

/**
 * Schema for every variable in .env.example. Validation runs once at
 * bootstrap (ConfigModule `validate`), so a missing or malformed value stops
 * the application immediately instead of failing on first use.
 *
 * New environment variables must be added here and to .env.example in the same
 * commit.
 *
 * Exported as a type as well as validated: it is what ConfigService is
 * parameterised with, so reading a variable under a name this class does not
 * declare stops the compiler rather than returning undefined at runtime. The
 * schema is therefore the single source of both the names and their types —
 * nothing else in the API spells an environment variable out.
 */
export class EnvironmentVariables {
  // --- окружение ---
  /**
   * Set by whatever starts the process, not by .env as a rule — it is declared
   * here because the mail guard below turns on it, and a typo such as "prod"
   * would switch that guard off without a word.
   */
  @IsOptional()
  @IsIn(NODE_ENV_NAMES)
  @SendsForRealInProduction()
  NODE_ENV?: (typeof NODE_ENV_NAMES)[number];

  // --- база данных ---
  @IsNotEmpty()
  @IsString()
  DB_HOST: string;

  @IsPortNumber()
  DB_PORT: number;

  @IsNotEmpty()
  @IsString()
  DB_USER: string;

  @IsNotEmpty()
  @IsString()
  DB_PASSWORD: string;

  @IsNotEmpty()
  @IsString()
  DB_NAME: string;

  // --- приложение ---
  /**
   * Both carry their default here, so ConfigService always hands back a value
   * and no caller substitutes its own. They are not optional to the
   * application — only to whoever writes the .env.
   */
  @IsPortNumber()
  PORT: number = DEFAULT_PORT;

  @IsNotEmpty()
  @IsString()
  HOST: string = DEFAULT_HOST;

  /**
   * Required, and an absolute address: the mail skeleton builds every link of
   * every email from it, including the unsubscribe link each message must
   * carry. require_tld is off on purpose — http://localhost:3000 of
   * .env.example would otherwise fail and break local development.
   */
  @IsNotEmpty()
  @IsUrl({
    require_tld: false,
    require_protocol: true,
    protocols: ['http', 'https'],
  })
  @Matches(ORIGIN_ONLY, {
    message:
      'FRONTEND_URL must carry a scheme and a host only, with no path prefix',
  })
  FRONTEND_URL: string;

  // --- секреты ---
  @IsSecret()
  JWT_SECRET: string;

  @IsSecret()
  JWT_REFRESH_SECRET: string;

  @IsSecret()
  COOKIE_SECRET: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(4)
  @Max(31)
  SALT_ROUNDS?: number;

  @IsOptional()
  @IsString()
  ACCESS_TOKEN_EXPIRY?: string;

  @IsOptional()
  @IsString()
  REFRESH_TOKEN_EXPIRY?: string;

  @IsOptional()
  @Transform(({ value }) => value === 'true' || value === true)
  @IsBoolean()
  HTTPS_ENABLED?: boolean;

  // --- почта ---
  /**
   * Required: the mail skeleton refuses to compose a message without a sender
   * address, and the refusal would otherwise surface at the first send — in a
   * nightly job, with nobody watching. The address lives here and only here:
   * changing it is an edit of .env, never of code.
   */
  @IsNotEmpty()
  @IsEmail()
  @AtSenderDomain()
  MAIL_FROM: string;

  /**
   * Which transport sends. Unset means the local one: a fresh clone runs, and
   * develops against, an API that needs no provider account — production is
   * held to the opposite by the guard on NODE_ENV above.
   */
  @IsOptional()
  @IsIn(MAIL_TRANSPORT_NAMES)
  MAIL_TRANSPORT?: MailTransportName;

  /**
   * Where the local transport writes. Unset means .mail-outbox, and the default
   * is applied here rather than in the transport, so that the transport is
   * always handed a directory. Empty is not unset: it would resolve to the
   * working directory, and the files carry real addresses in their To: header
   * while only .mail-outbox is in .gitignore.
   *
   * The name itself comes from src/mail, like the list of transport names
   * above: the schema validates what the module declares, never the other way
   * round.
   */
  @IsNotEmpty()
  @IsString()
  MAIL_OUTBOX_DIR: string = DEFAULT_MAIL_OUTBOX_DIR;

  /**
   * The domain verified at the provider (SPF, DKIM, DMARC). MAIL_FROM is
   * checked against it at bootstrap (see AtSenderDomain above) — a typo in the
   * sender address otherwise surfaces as mail silently refused by the
   * provider. A domain, not a URL: that is what the part after the @ is
   * compared with.
   *
   * Required of the sending transport, and checked for shape wherever it is
   * written: the check above reads it under every transport, so a URL left
   * here would stop the application with "MAIL_FROM is wrong" while MAIL_FROM
   * is right — and the operator would go inspect the wrong line.
   */
  @ValidateIf(
    (env: EnvironmentVariables) =>
      sendsForReal(env) || Boolean(env.MAIL_SENDER_DOMAIN?.trim()),
  )
  @IsNotEmpty()
  @IsFQDN()
  MAIL_SENDER_DOMAIN?: string;

  /**
   * Credentials of the provider, required only when it is the transport: they
   * are what a local clone must not need. Missing here stops the application at
   * bootstrap rather than at the first send — which happens in a nightly job,
   * with nobody watching.
   */
  @ValidateIf(sendsForReal)
  @IsNotEmpty()
  @IsString()
  SCW_SECRET_KEY?: string;

  /** A UUID at Scaleway; checked as one so the two values above cannot be swapped. */
  @ValidateIf(sendsForReal)
  @IsNotEmpty()
  @IsUUID()
  SCW_PROJECT_ID?: string;
}

export function validateEnv(
  config: Record<string, unknown>,
): EnvironmentVariables {
  const validated = plainToInstance(EnvironmentVariables, config);
  const errors = validateSync(validated, { whitelist: false });

  if (errors.length > 0) {
    // Only property names and constraint messages: values may be secrets.
    const details = errors
      .map((error) => Object.values(error.constraints ?? {}).join('; '))
      .join('\n  ');
    throw new Error(`Invalid environment configuration:\n  ${details}`);
  }

  return validated;
}
